/* Shared project catalogue — single source of truth for all Projects pages.
   IOT_PROJECTS (100) + AI_PROJECTS (25). Counts derived dynamically elsewhere. */
window.IOT_PROJECTS = [
    {no:"001",cat:"Smart Home",title:"Smart Door Lock",desc:"Keypad, RFID and app-based unlock with cloud entry logs and remote access.",tags:["ESP32","RFID","App"]},
    {no:"002",cat:"Smart Home",title:"Voice-Controlled Home Hub",desc:"Offline voice assistant that switches lights, fans and appliances on command.",tags:["Voice","Automation","MQTT"]},
    {no:"003",cat:"Smart Home",title:"Learning Smart Thermostat",desc:"Auto temperature control that learns routines and schedules heating and cooling.",tags:["Sensors","ML","HVAC"]},
    {no:"004",cat:"Smart Home",title:"Automated Curtain System",desc:"Motorized curtains that open and close by light level, time, or app.",tags:["Motors","Light","App"]},
    {no:"005",cat:"Smart Home",title:"Smart Plug Energy Monitor",desc:"Per-socket power tracking, scheduling, and remote switching from your phone.",tags:["Energy","WiFi","App"]},
    {no:"006",cat:"Smart Home",title:"Water Leak & Flood Detector",desc:"Floor-level water sensors that fire instant phone alerts before damage spreads.",tags:["Sensors","Alerts","Safety"]},
    {no:"007",cat:"Smart Home",title:"Smart Video Doorbell",desc:"Motion alerts, two-way audio, and recorded clips of every visitor.",tags:["Camera","Audio","App"]},
    {no:"008",cat:"Smart Home",title:"Indoor Air Quality Monitor",desc:"Tracks CO2, PM2.5 and VOCs with a live dashboard and ventilation alerts.",tags:["Sensors","AQI","Dashboard"]},
    {no:"009",cat:"Smart Home",title:"Smart Lighting Mesh",desc:"Room-aware RGBW lighting that follows presence, mood and time of day.",tags:["Mesh","RGBW","Automation"]},
    {no:"010",cat:"Smart Home",title:"Gas Leak Detector + Auto Shutoff",desc:"Detects LPG/CO and automatically closes the gas valve while alerting you.",tags:["Safety","Sensors","Relay"]},
    {no:"011",cat:"Smart Home",title:"Smart Plant Irrigation",desc:"Soil-moisture sensing that waters indoor plants only when they need it.",tags:["Soil","Pump","App"]},
    {no:"012",cat:"Smart Home",title:"Sleep Environment Optimizer",desc:"Tunes bedroom temperature, light and sound for deeper, healthier sleep.",tags:["Sensors","Comfort","Automation"]},
    {no:"013",cat:"Smart Home",title:"Smart Mirror",desc:"A two-way mirror showing weather, calendar, news and reminders at a glance.",tags:["Display","API","UI"]},
    {no:"014",cat:"Smart Home",title:"Smart Pet Feeder & Monitor",desc:"Scheduled portioned feeding with a live camera to check on your pet.",tags:["Camera","Scheduler","App"]},

    {no:"015",cat:"Health & Wearables",title:"Heart-Rate & SpO2 Band",desc:"A wrist wearable that continuously logs pulse and blood-oxygen levels.",tags:["Wearable","BLE","Health"]},
    {no:"016",cat:"Health & Wearables",title:"Fall Detection Pendant",desc:"Detects sudden falls and alerts family or caregivers with location.",tags:["IMU","Elderly","Alerts"]},
    {no:"017",cat:"Health & Wearables",title:"Smart Pill Dispenser",desc:"Times and dispenses medication with reminders and missed-dose alerts.",tags:["Health","Scheduler","Alerts"]},
    {no:"018",cat:"Health & Wearables",title:"Posture Correction Wearable",desc:"Senses slouching and nudges you upright with gentle haptic feedback.",tags:["IMU","Haptics","Wearable"]},
    {no:"019",cat:"Health & Wearables",title:"Continuous Fever Patch",desc:"A skin patch that streams body temperature for round-the-clock monitoring.",tags:["Sensor","BLE","Health"]},
    {no:"020",cat:"Health & Wearables",title:"Sleep Apnea Tracker",desc:"Monitors breathing and snoring patterns to flag possible apnea events.",tags:["Audio","Sensors","Health"]},
    {no:"021",cat:"Health & Wearables",title:"Hydration Reminder Bottle",desc:"A smart bottle that tracks water intake and reminds you to drink.",tags:["Sensor","App","Wellness"]},
    {no:"022",cat:"Health & Wearables",title:"Pocket ECG Monitor",desc:"Captures single-lead heart rhythm and syncs traces to the cloud.",tags:["ECG","BLE","Health"]},
    {no:"023",cat:"Health & Wearables",title:"Baby Breathing Monitor",desc:"Crib sensor that watches infant breathing and movement, alerting on pauses.",tags:["Sensors","Safety","Alerts"]},
    {no:"024",cat:"Health & Wearables",title:"Blood Pressure Logger",desc:"A connected cuff that records BP history and trends to your phone.",tags:["Health","BLE","Cloud"]},
    {no:"025",cat:"Health & Wearables",title:"Stress & HRV Wearable",desc:"Reads heart-rate variability and guides breathing to lower stress.",tags:["HRV","Wearable","Wellness"]},
    {no:"026",cat:"Health & Wearables",title:"Smart Insole Gait Analyzer",desc:"Pressure-sensing insole that analyzes steps, balance and walking patterns.",tags:["Pressure","Wearable","Analytics"]},

    {no:"027",cat:"Agriculture",title:"Smart Greenhouse Controller",desc:"Automates climate, ventilation and irrigation for optimal plant growth.",tags:["Climate","Automation","Sensors"]},
    {no:"028",cat:"Agriculture",title:"Soil NPK Sensor Node",desc:"Measures nitrogen, phosphorus and potassium to guide precise fertilizing.",tags:["Soil","Sensors","Farming"]},
    {no:"029",cat:"Agriculture",title:"Automated Drip Irrigation",desc:"Delivers water on crop-stage schedules driven by live soil readings.",tags:["Irrigation","Soil","Pump"]},
    {no:"030",cat:"Agriculture",title:"Livestock Health Collar",desc:"Tracks cattle temperature and activity to catch illness early.",tags:["Wearable","Animal","Sensors"]},
    {no:"031",cat:"Agriculture",title:"Crop Disease Camera",desc:"Images leaves and flags early signs of disease for quick action.",tags:["Camera","Vision","Farming"]},
    {no:"032",cat:"Agriculture",title:"Farm Weather Station",desc:"Hyperlocal rain, wind, humidity and temperature for the field.",tags:["Weather","Sensors","Cloud"]},
    {no:"033",cat:"Agriculture",title:"Grain Silo Monitor",desc:"Tracks moisture and temperature inside silos to prevent spoilage.",tags:["Sensors","Storage","Alerts"]},
    {no:"034",cat:"Agriculture",title:"Solar Pump Controller",desc:"Smartly runs a solar borewell pump based on tank level and sunlight.",tags:["Solar","Pump","Automation"]},
    {no:"035",cat:"Agriculture",title:"Beehive Health Monitor",desc:"Logs hive weight, temperature and humidity to track colony health.",tags:["Sensors","Apiary","Cloud"]},
    {no:"036",cat:"Agriculture",title:"Smart Pest Trap Counter",desc:"Counts trapped insects automatically and reports infestation trends.",tags:["Sensor","Vision","Farming"]},
    {no:"037",cat:"Agriculture",title:"Cold Storage Monitor",desc:"Keeps produce temperature in range with compliance logs and alerts.",tags:["Cold-chain","Sensors","Alerts"]},
    {no:"038",cat:"Agriculture",title:"Aquaponics Controller",desc:"Balances pH and dissolved oxygen for fish and plants together.",tags:["pH","Automation","Sensors"]},

    {no:"039",cat:"Environment",title:"City Air Pollution Node",desc:"A low-cost node feeding distributed, street-level air-quality maps.",tags:["AQI","Sensors","Cloud"]},
    {no:"040",cat:"Environment",title:"River Water Quality Buoy",desc:"Floating sensor logging pH, turbidity and dissolved oxygen in rivers.",tags:["Water","Sensors","Telemetry"]},
    {no:"041",cat:"Environment",title:"Noise Pollution Mapper",desc:"Measures urban sound levels to build city-wide noise heat maps.",tags:["Audio","Sensors","Mapping"]},
    {no:"042",cat:"Environment",title:"Forest Fire Early Detector",desc:"Wireless smoke and heat nodes that warn of wildfires within minutes.",tags:["Sensors","LoRa","Safety"]},
    {no:"043",cat:"Environment",title:"Flood Level Sensor",desc:"Ultrasonic riverbank sensing that issues early flood warnings.",tags:["Ultrasonic","Alerts","Safety"]},
    {no:"044",cat:"Environment",title:"UV Index Public Monitor",desc:"Displays live UV exposure levels for parks and public spaces.",tags:["Sensor","Display","Health"]},
    {no:"045",cat:"Environment",title:"Landfill Methane Monitor",desc:"Detects methane buildup and leaks across waste sites.",tags:["Gas","Sensors","Safety"]},
    {no:"046",cat:"Environment",title:"Earthquake Vibration Sensor",desc:"Community seismic node that triggers fast local shake alerts.",tags:["Accel","Alerts","Safety"]},
    {no:"047",cat:"Environment",title:"Rainwater Harvesting Monitor",desc:"Tracks tank level and water quality for harvesting systems.",tags:["Water","Sensors","App"]},
    {no:"048",cat:"Environment",title:"High-Altitude Telemetry Node",desc:"Rugged remote sensing of weather in glaciers and mountains.",tags:["LoRa","Weather","Remote"]},

    {no:"049",cat:"Security",title:"Smart CCTV Motion Alerts",desc:"Edge motion detection that records and notifies only on real events.",tags:["Camera","Edge","Alerts"]},
    {no:"050",cat:"Security",title:"Perimeter Laser Trip Sensor",desc:"Line-break beams that detect intrusions along a boundary.",tags:["Laser","Alarm","Security"]},
    {no:"051",cat:"Security",title:"RFID Access Control",desc:"Card-based door access with role permissions and full audit logs.",tags:["RFID","Access","Logs"]},
    {no:"052",cat:"Security",title:"Number-Plate Gate Logger",desc:"Reads vehicle plates to log and automate entry and exit.",tags:["Vision","ANPR","Gate"]},
    {no:"053",cat:"Security",title:"Panic Button Network",desc:"Campus or society SOS buttons that route alerts to a control room.",tags:["SOS","Mesh","Safety"]},
    {no:"054",cat:"Security",title:"Smart Tamper Safe",desc:"A lockbox with access logs and instant tamper notifications.",tags:["Lock","Sensors","Alerts"]},
    {no:"055",cat:"Security",title:"Door/Window Breach Alarm",desc:"Magnetic contacts that detect openings and sound a networked alarm.",tags:["Magnet","Alarm","Mesh"]},
    {no:"056",cat:"Security",title:"Networked Fire & Smoke Alarm",desc:"Building-wide smoke detection with coordinated, location-aware alerts.",tags:["Smoke","Mesh","Safety"]},
    {no:"057",cat:"Security",title:"Asset GPS Tracker",desc:"Tracks high-value equipment and flags movement outside safe zones.",tags:["GPS","Geofence","Theft"]},
    {no:"058",cat:"Security",title:"Visitor Management Kiosk",desc:"QR-based check-in with photo capture and digital visitor logs.",tags:["QR","Kiosk","Logs"]},

    {no:"059",cat:"Industrial",title:"Machine Vibration Monitor",desc:"Senses abnormal vibration to predict bearing and motor failures.",tags:["Predictive","Accel","Industry"]},
    {no:"060",cat:"Industrial",title:"Factory Energy Dashboard",desc:"Tracks per-machine power use to cut waste and spot anomalies.",tags:["Energy","Dashboard","Industry"]},
    {no:"061",cat:"Industrial",title:"Conveyor Item Counter",desc:"Counts products on the line for accurate, automatic production tallies.",tags:["Sensor","Counting","Industry"]},
    {no:"062",cat:"Industrial",title:"Predictive Motor Temperature",desc:"Watches motor heat to warn before overheating shuts the line down.",tags:["Thermal","Predictive","Alerts"]},
    {no:"063",cat:"Industrial",title:"Digital Twin Gateway",desc:"Bridges live plant sensor data into a real-time digital twin.",tags:["Gateway","Telemetry","Industry"]},
    {no:"064",cat:"Industrial",title:"Remote Tank Level Telemetry",desc:"Monitors fuel and chemical tank levels from anywhere.",tags:["Level","Telemetry","Cloud"]},
    {no:"065",cat:"Industrial",title:"OEE Productivity Tracker",desc:"Logs uptime, speed and quality to compute machine efficiency.",tags:["OEE","Analytics","Industry"]},
    {no:"066",cat:"Industrial",title:"Compressed Air Leak Monitor",desc:"Finds costly air leaks that quietly drain factory energy.",tags:["Energy","Sensors","Industry"]},
    {no:"067",cat:"Industrial",title:"Worker Safety Wearable",desc:"Detects toxic gas and man-down events to protect plant workers.",tags:["Gas","Wearable","Safety"]},
    {no:"068",cat:"Industrial",title:"Warehouse Climate Logger",desc:"Records humidity and temperature for storage compliance audits.",tags:["Sensors","Logs","Storage"]},

    {no:"069",cat:"Energy",title:"Solar Rooftop Monitor",desc:"Tracks generation and detects panel faults on rooftop solar.",tags:["Solar","Monitoring","Cloud"]},
    {no:"070",cat:"Energy",title:"Smart Energy Meter",desc:"Real-time home consumption with appliance-level insights.",tags:["Energy","Metering","App"]},
    {no:"071",cat:"Energy",title:"EV Charging Controller",desc:"Smart load management and usage billing for EV charge points.",tags:["EV","Charging","Billing"]},
    {no:"072",cat:"Energy",title:"Battery Management Monitor",desc:"Watches pack voltage, temperature and balancing for safe storage.",tags:["BMS","Battery","Safety"]},
    {no:"073",cat:"Energy",title:"Grid Power-Quality Logger",desc:"Captures voltage sags and surges to diagnose supply problems.",tags:["Grid","Sensors","Logs"]},
    {no:"074",cat:"Energy",title:"Streetlight Energy Optimizer",desc:"Dusk-to-dawn control with dimming to cut municipal power bills.",tags:["Lighting","Energy","Automation"]},
    {no:"075",cat:"Energy",title:"Home Solar + Battery Optimizer",desc:"Maximizes self-consumption by shifting loads to solar hours.",tags:["Solar","Battery","Logic"]},
    {no:"076",cat:"Energy",title:"Generator Run-Hour Monitor",desc:"Logs diesel genset usage and fuel burn for maintenance planning.",tags:["Genset","Logs","Cloud"]},

    {no:"077",cat:"Smart City",title:"Smart Parking Sensor Grid",desc:"Bay-level occupancy sensing that guides drivers to free spots.",tags:["Parking","Sensors","App"]},
    {no:"078",cat:"Smart City",title:"Smart Waste Bin",desc:"Fill-level sensing that optimizes garbage collection routes.",tags:["Waste","Sensors","Routing"]},
    {no:"079",cat:"Smart City",title:"Adaptive Traffic Signal",desc:"Adjusts signal timing to live traffic density to ease congestion.",tags:["Traffic","Vision","City"]},
    {no:"080",cat:"Smart City",title:"Public Transit Tracker",desc:"Live bus location and ETA beacons for riders at every stop.",tags:["GPS","Transit","App"]},
    {no:"081",cat:"Smart City",title:"Smart Streetlight Network",desc:"Centrally controlled streetlights with fault and brightness reporting.",tags:["Lighting","Mesh","City"]},
    {no:"082",cat:"Smart City",title:"Water Pipeline Leak Detector",desc:"Pressure analytics that pinpoint leaks across the supply network.",tags:["Water","Pressure","City"]},
    {no:"083",cat:"Smart City",title:"Manhole Safety Monitor",desc:"Tracks sewer level and toxic gas for worker and flood safety.",tags:["Gas","Level","Safety"]},
    {no:"084",cat:"Smart City",title:"Digital Signage Controller",desc:"Manages networked public displays with remote content scheduling.",tags:["Display","Network","City"]},

    {no:"085",cat:"Automotive",title:"OBD-II Fleet Tracker",desc:"Vehicle health, location and driving telematics for fleets.",tags:["OBD","GPS","Fleet"]},
    {no:"086",cat:"Automotive",title:"Driver Drowsiness Alert",desc:"Detects eye and head signs of fatigue and warns the driver.",tags:["Vision","Safety","Alerts"]},
    {no:"087",cat:"Automotive",title:"Tire Pressure Monitor",desc:"Wireless TPMS that surfaces live pressures on a dashboard.",tags:["TPMS","Wireless","Safety"]},
    {no:"088",cat:"Automotive",title:"EV Range & Trip Logger",desc:"Logs energy-per-kilometre and trip efficiency for EV owners.",tags:["EV","Analytics","App"]},
    {no:"089",cat:"Automotive",title:"Cold-Chain Truck Monitor",desc:"Keeps cargo in temperature range with route compliance logs.",tags:["Cold-chain","GPS","Sensors"]},
    {no:"090",cat:"Automotive",title:"Two-Wheeler Anti-Theft GPS",desc:"Geofencing and remote immobilizer to deter bike theft.",tags:["GPS","Geofence","Security"]},

    {no:"091",cat:"Robotics",title:"Line-Following Delivery Bot",desc:"An indoor courier that follows a path to ferry items autonomously.",tags:["Robot","Sensors","Autonomy"]},
    {no:"092",cat:"Robotics",title:"Obstacle-Avoiding Rover",desc:"An ultrasonic buggy that navigates around obstacles on its own.",tags:["Robot","Ultrasonic","Autonomy"]},
    {no:"093",cat:"Robotics",title:"4-DOF Robotic Arm",desc:"A controllable arm for pick-and-place and learning kinematics.",tags:["Robot","Servos","Control"]},
    {no:"094",cat:"Robotics",title:"Self-Balancing Robot",desc:"A two-wheel robot that stays upright using an IMU and PID control.",tags:["IMU","PID","Robot"]},
    {no:"095",cat:"Robotics",title:"Warehouse AGV Prototype",desc:"A guided vehicle that moves materials along defined warehouse routes.",tags:["AGV","Robot","Logistics"]},
    {no:"096",cat:"Robotics",title:"Telepresence Robot",desc:"A remotely driven camera bot for presence in another location.",tags:["Robot","Camera","Remote"]},

    {no:"097",cat:"Retail",title:"Smart Shelf Stock Sensor",desc:"Weight-based shelves that flag low stock for instant restocking.",tags:["Weight","Retail","Alerts"]},
    {no:"098",cat:"Retail",title:"Queue Length Counter",desc:"Counts shoppers in line to optimize checkout staffing.",tags:["Vision","Analytics","Retail"]},
    {no:"099",cat:"Retail",title:"Smart Vending Telemetry",desc:"Reports stock and sales from vending machines in real time.",tags:["Telemetry","Retail","Cloud"]},
    {no:"100",cat:"Retail",title:"NFC Smart Attendance",desc:"Tap-in attendance tracking for offices, schools and events.",tags:["NFC","Attendance","Logs"]}
  ];

window.AI_PROJECTS = [
    {no:"A01",cat:"Robotics & Autonomy",featured:true,url:"rover.html",title:"Rover — AI Robot Dog",desc:"A 3D-printed, four-legged companion robot with on-board AI, servo-driven gait and vision. My flagship build.",tags:["Robotics","AI","3D Printing"]},
    {no:"A02",cat:"Computer Vision",title:"Real-Time Object Detection",desc:"A YOLO-based detector that finds and labels multiple objects in a live video stream.",tags:["YOLO","Vision","Real-time"]},
    {no:"A03",cat:"Computer Vision",title:"Face Recognition Attendance",desc:"Face-based attendance with liveness checks to stop photo spoofing.",tags:["Face","CNN","Anti-spoof"]},
    {no:"A04",cat:"Computer Vision",title:"Sign Language Translator",desc:"Translates hand-sign gestures into text in real time using pose and vision models.",tags:["Vision","Gesture","Accessibility"]},
    {no:"A05",cat:"Computer Vision",title:"Pose-Estimation Fitness Coach",desc:"Counts reps and gives live form feedback by tracking body keypoints.",tags:["Pose","Vision","Health"]},
    {no:"A06",cat:"Computer Vision",title:"License Plate Recognition",desc:"An ANPR pipeline that detects and reads vehicle number plates from camera feeds.",tags:["ANPR","OCR","Vision"]},
    {no:"A07",cat:"Computer Vision",title:"Crop Disease Classifier",desc:"A CNN that diagnoses plant leaf diseases from a single phone photo.",tags:["CNN","AgriTech","Vision"]},
    {no:"A08",cat:"Computer Vision",title:"Handwriting & OCR Engine",desc:"Recognizes handwritten digits and text and converts pages into editable text.",tags:["OCR","Deep Learning","Vision"]},
    {no:"A09",cat:"NLP & LLM",title:"AI Resume Screener",desc:"Ranks resumes against a job description using NLP relevance scoring.",tags:["NLP","Ranking","HR"]},
    {no:"A10",cat:"NLP & LLM",title:"Sentiment Analysis Engine",desc:"Mines opinion and emotion from reviews and social posts at scale.",tags:["NLP","Sentiment","Analytics"]},
    {no:"A11",cat:"NLP & LLM",title:"Document Q&A (RAG)",desc:"Chat over your own PDFs and docs with retrieval-augmented generation.",tags:["LLM","RAG","Search"]},
    {no:"A12",cat:"NLP & LLM",title:"Multilingual Chatbot",desc:"A context-aware assistant that converses fluently across Indian languages.",tags:["LLM","Chatbot","Multilingual"]},
    {no:"A13",cat:"NLP & LLM",title:"Abstractive Text Summarizer",desc:"Condenses long documents into crisp, readable summaries.",tags:["NLP","Summarization","LLM"]},
    {no:"A14",cat:"Generative AI",title:"Generative Image Model",desc:"Creates original artwork and images from text prompts using diffusion.",tags:["Diffusion","GenAI","Art"]},
    {no:"A15",cat:"Generative AI",title:"AI Code Assistant",desc:"An LLM-powered helper that explains, writes and refactors code.",tags:["LLM","Coding","DevTools"]},
    {no:"A16",cat:"Speech & Audio",title:"Wake-Word Voice Assistant",desc:"On-device wake-word detection with offline voice command handling.",tags:["Speech","Edge","Voice"]},
    {no:"A17",cat:"Speech & Audio",title:"Speech-to-Text Transcriber",desc:"Real-time transcription with speaker diarization for meetings.",tags:["ASR","Speech","Real-time"]},
    {no:"A18",cat:"Speech & Audio",title:"Music Genre Classifier",desc:"Classifies songs into genres from extracted audio features.",tags:["Audio","ML","Classification"]},
    {no:"A19",cat:"Predictive ML",title:"Stock Trend Predictor",desc:"Time-series models that forecast market direction and volatility.",tags:["Time-series","Finance","ML"]},
    {no:"A20",cat:"Predictive ML",title:"Energy Demand Forecaster",desc:"Predicts electricity load for grids and homes to plan supply.",tags:["Forecasting","Energy","ML"]},
    {no:"A21",cat:"Predictive ML",title:"Fraud Detection Model",desc:"Flags suspicious transactions in real time using anomaly detection.",tags:["Anomaly","Finance","ML"]},
    {no:"A22",cat:"Predictive ML",title:"Recommendation Engine",desc:"Personalizes content and products with collaborative filtering.",tags:["RecSys","ML","Personalization"]},
    {no:"A23",cat:"Robotics & Autonomy",title:"Autonomous Lane-Keeping Car",desc:"A vision-driven model car that steers itself to stay in its lane.",tags:["Self-driving","Vision","Control"]},
    {no:"A24",cat:"Robotics & Autonomy",title:"Gesture-Controlled Drone",desc:"Fly a drone with hand gestures interpreted by a vision model.",tags:["Drone","Gesture","Vision"]},
    {no:"A25",cat:"Edge AI",title:"Edge AI Smart Camera",desc:"On-device person and vehicle analytics with no cloud round-trip.",tags:["Edge","Vision","Privacy"]}
  ];

window.ALL_PROJECTS = [].concat(window.IOT_PROJECTS, window.AI_PROJECTS);

/* docs:start — generated by projects/_build/build.js, do not edit by hand.
   Maps a catalogue project number to its documentation page slug so that
   projects.js can turn every card into a link to its full build guide. */
window.PROJECT_DOCS = {"001":"smart-door-lock","002":"voice-controlled-home-hub"};
/* docs:end */
