/* ============================================================
   Per-article image assignment for the Journal generator.
   - cr:  credit line for each image file (shown in <figcaption>)
   - MAP: slug -> { hero:[file,alt,'contain'?], inline:[[file,alt],...] }
   build.js overrides each article's hero and injects the inline
   images into the body at evenly spaced positions.
   ============================================================ */
'use strict';
const W = 'via <a href="https://commons.wikimedia.org/" rel="nofollow noopener" target="_blank">Wikimedia Commons</a>.';
const L = {
  bysa4: '<a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="nofollow noopener" target="_blank">CC BY-SA 4.0</a>',
  bysa3: '<a href="https://creativecommons.org/licenses/by-sa/3.0/" rel="nofollow noopener" target="_blank">CC BY-SA 3.0</a>',
  by4: '<a href="https://creativecommons.org/licenses/by/4.0/" rel="nofollow noopener" target="_blank">CC BY 4.0</a>',
  by3: '<a href="https://creativecommons.org/licenses/by/3.0/" rel="nofollow noopener" target="_blank">CC BY 3.0</a>',
  by2: '<a href="https://creativecommons.org/licenses/by/2.0/" rel="nofollow noopener" target="_blank">CC BY 2.0</a>',
  cc0: '<a href="https://creativecommons.org/publicdomain/zero/1.0/" rel="nofollow noopener" target="_blank">CC0</a>',
  pd: 'Public Domain',
  godl: 'GODL-India'
};
const cr = {
  'national-war-memorial.jpg': `Photograph by Sanket Oswal, ${L.bysa4}, ${W}`,
  'param-vir-chakra.png': `Image: Government of India, ${L.pd}, ${W}`,
  'kargil-war-memorial.jpg': `Photograph by PhotoholicAbhishek, ${L.bysa4}, ${W}`,
  'amar-jawan-jyoti.jpg': `Photograph by KCVelaga, ${L.bysa4}, ${W}`,
  'republic-day.jpg': `Photograph: Government of India, ${L.godl}, ${W}`,
  'siachen.jpg': `Photograph by Arshsangh, ${L.bysa4}, ${W}`,
  'manekshaw.jpg': `Photograph: Indian Army / Government of India, ${L.godl}, ${W}`,
  'ins-vikrant.jpg': `Photograph: Indian Navy / Government of India, ${L.godl}, ${W}`,
  'iaf-rafale.jpg': `Photograph: Indian Air Force / Government of India, ${W}`,
  'army-mountains.jpg': `Photograph: U.S. Army, ${L.pd}, ${W}`,
  'nathula-pass.jpg': `Photograph by $udeep Bajpai, ${L.by2}, ${W}`,
  'nathula-sikkim.jpg': `Photograph by Debapriya Hore, ${L.bysa4}, ${W}`,
  '1971-surrender.jpg': `Photograph: Ministry of Liberation War Affairs (Bangladesh), ${L.pd}, ${W}`,
  'tiger-hill.jpg': `Photograph by taNvir kohli, ${L.by2}, ${W}`,
  'kargil-memorial-2.jpg': `Photograph by Liginjo, ${L.bysa4}, ${W}`,
  'kargil-memorial-entrance.jpg': `Photograph by Liginjo, ${L.bysa4}, ${W}`,
  'taj-mumbai.jpg': `Photograph by Joe Ravi, ${L.bysa3}, ${W}`,
  'gateway-taj.jpg': `Photograph by iMahesh, ${L.bysa4}, ${W}`,
  'paratroopers.jpg': `Photograph: U.S. Army (Sgt. Mike MacLeod), ${L.pd}, ${W}`,
  'tejas.jpg': `Photograph by Rahuldevnath, ${L.by3}, ${W}`,
  'tejas-mk1a.jpg': `Photograph by InSameer, ${L.bysa4}, ${W}`,
  'salt-march.jpg': `Photograph of the 1930 Salt March, ${L.pd}, ${W}`,
  'gandhi-dandi.jpg': `Gandhi at Dandi, 1930, ${L.pd}, ${W}`,
  'saragarhi-memorial.jpg': `Photograph by RameshSharma1, ${L.by2}, ${W}`,
  'gorkha-bicentenary.jpg': `Photograph: Ministry of Defence, ${L.godl}, ${W}`,
  'brahmos.jpg': `Photograph by Mike1979 Russia, ${L.bysa3}, ${W}`,
  't90-exercise.jpg': `Photograph: U.S. DoD (Fred W. Baker III), ${L.pd}, ${W}`,
  't90-tank.jpg': `Photograph: Ministry of Defence (Dipak Das), ${L.godl}, ${W}`,
  'india-gate.jpg': `Photograph by Yann, ${L.bysa3}, ${W}`,
  'navy-submarine.jpg': `Photograph: Indian Navy, ${L.godl}, ${W}`,
  'mirage-refuel.jpg': `Photograph: Indian Air Force, ${L.godl}, ${W}`,
  'avani-chaturvedi.jpg': `Photograph: Ministry of Defence, ${L.godl}, ${W}`,
  'pangong-tso.jpg': `Photograph by Vimal Chaunkaria, ${L.bysa4}, ${W}`,
  'rezangla-site.jpg': `Photograph by Runabhattacharjee, ${L.cc0}, ${W}`,
  'redfort-independence.jpg': `Independence Day at the Red Fort, ${L.pd}, ${W}`,
  'vikram-batra-portrait.jpg': `Photograph: Indian Army / Government of India, ${L.godl}, ${W}`,
  'somnath-sharma-stamp.jpg': `Image: India Post, ${L.godl}, ${W}`,
  'somnath-sharma-statue.jpg': `Photograph by KCVelaga, ${L.bysa4}, ${W}`,
  'marcos-parachute.jpg': `Photograph: Ministry of Defence (Rakesh Mangraj), ${L.godl}, ${W}`,
  'mig21.jpg': `Photograph by Sanil Nath, ${L.by4}, ${W}`,
  'army-training.jpg': `Photograph: U.S. Army (Sgt. Michael J. MacLeod), ${L.pd}, ${W}`,
  'cariappa.jpg': `Photograph: Indian Army / Government of India, ${L.godl}, ${W}`,
  'bipin-rawat.jpg': `Photograph: Integrated Defence Staff / Government of India, ${L.godl}, ${W}`,
  'coast-guard.jpg': `Photograph by BellaNYork, ${L.cc0}, ${W}`,
  'agni-missile.jpg': `Photograph: Ministry of Defence / Government of India, ${L.godl}, ${W}`,
  'republic-2025.jpg': `Photograph: Government of India (montage by 8bhakt), ${L.godl}, ${W}`
};

const MAP = {
  'battle-of-nathu-la-1967':        { hero:['nathula-pass.jpg','The Nathu La pass on the India–China border in Sikkim'], inline:[['nathula-sikkim.jpg','The high, wind-scoured terrain of the Nathu La pass'],['army-mountains.jpg','Indian Army soldiers at a high-altitude Himalayan post']] },
  '1971-war-birth-of-bangladesh':   { hero:['1971-surrender.jpg','The Pakistani Instrument of Surrender, signed in Dhaka on 16 December 1971'], inline:[['manekshaw.jpg','General (later Field Marshal) Sam Manekshaw, who led the army in 1971']] },
  'captain-vikram-batra':           { hero:['vikram-batra-portrait.jpg','Captain Vikram Batra, PVC'], inline:[['tiger-hill.jpg','Tiger Hill, one of the Kargil peaks'],['kargil-war-memorial.jpg','The Kargil War Memorial at Drass']] },
  'veer-naris-families-who-serve':  { hero:['kargil-memorial-2.jpg','The wall of names at the Kargil War Memorial'], inline:[['amar-jawan-jyoti.jpg','The eternal flame of remembrance']] },
  'operation-parakram-2001':        { hero:['army-mountains.jpg','Indian Army soldiers deployed in a forward area'], inline:[['t90-exercise.jpg','An Indian Army T-90 main battle tank on exercise']] },
  'mumbai-26-11-nsg':               { hero:['taj-mumbai.jpg','The Taj Mahal Palace Hotel, Mumbai, a site of the 26/11 attacks'], inline:[['gateway-taj.jpg','The Gateway of India beside the Taj, Mumbai']] },
  'para-sf-surgical-strikes':       { hero:['paratroopers.jpg','Indian Army paratroopers of the Parachute Regiment'], inline:[['army-training.jpg','Indian Army soldiers in a field training exercise']] },
  'siachen-worlds-highest-battlefield': { hero:['siachen.jpg','Indian Army soldiers on the Siachen Glacier'], inline:[['pangong-tso.jpg','The high-altitude landscape of Ladakh']] },
  'garud-commandos-iaf':            { hero:['mirage-refuel.jpg','An Indian Air Force jet refuelling in flight'], inline:[['tejas-mk1a.jpg','An Indian Air Force fighter']] },
  'marcos-marine-commandos':        { hero:['marcos-parachute.jpg','An Indian Navy marine commando (MARCOS) parachuting during an exercise'], inline:[['gateway-taj.jpg','The Gateway of India, where MARCOS have conducted demonstrations']] },
  'raw-indias-silent-warriors':     { hero:['navy-submarine.jpg','An Indian Navy submarine — silent and unseen'], inline:[['amar-jawan-jyoti.jpg','The eternal flame honouring India’s unknown soldiers']] },
  'the-folded-pride-indian-flag':   { hero:['redfort-independence.jpg','The tricolour at the Red Fort on Independence Day'], inline:[['republic-day.jpg','The tricolour carried at the Republic Day parade']] },
  'field-marshal-sam-manekshaw':    { hero:['manekshaw.jpg','Field Marshal Sam Manekshaw'], inline:[['1971-surrender.jpg','The 1971 Instrument of Surrender — Manekshaw’s greatest victory']] },
  'major-somnath-sharma':           { hero:['somnath-sharma-statue.jpg','Statue of Major Somnath Sharma at the National War Memorial, Delhi'], inline:[['somnath-sharma-stamp.jpg','India Post commemorative stamp honouring Major Somnath Sharma'],['param-vir-chakra.png','The Param Vir Chakra']] },
  'galwan-valley-2020':             { hero:['pangong-tso.jpg','Pangong Tso and the high mountains of eastern Ladakh'], inline:[['army-mountains.jpg','Indian Army soldiers in the high mountains of Ladakh']] },
  'operation-sindoor-2025':         { hero:['iaf-rafale.jpg','An Indian Air Force Rafale, of the kind used in 2025'], inline:[['brahmos.jpg','A BrahMos missile, part of India’s precision-strike arsenal']] },
  'indian-navy-ins-vikrant':        { hero:['ins-vikrant.jpg','The aircraft carrier INS Vikrant with its battle group'], inline:[['navy-submarine.jpg','Indian Navy submarines']] },
  'indian-air-force-modern-power':  { hero:['tejas.jpg','The indigenous HAL Tejas light combat aircraft'], inline:[['mig21.jpg','An Indian Air Force MiG-21, a long-serving fighter']] },
  'battle-of-saragarhi-1897':       { hero:['saragarhi-memorial.jpg','The Saragarhi Memorial'], inline:[['gorkha-bicentenary.jpg','Soldiers paying homage at a war memorial']] },
  'gorkha-regiments':               { hero:['gorkha-bicentenary.jpg','A Gorkha Brigade ceremony at the Amar Jawan Jyoti'], inline:[['saragarhi-memorial.jpg','A memorial to soldierly sacrifice']] },
  '1965-war-asal-uttar':            { hero:['t90-tank.jpg','An Indian Army T-90 tank on parade — heir to the armour of 1965'], inline:[['republic-day.jpg','The Indian Army on parade']] },
  '1962-sino-indian-war':           { hero:['rezangla-site.jpg','The Rezang La war memorial site'], inline:[['army-mountains.jpg','Indian soldiers in the high Himalaya']] },
  'balakot-airstrike-2019':         { hero:['mig21.jpg','An Indian Air Force MiG-21, flown by Wing Commander Abhinandan in 2019'], inline:[['mirage-refuel.jpg','An Indian Air Force Mirage-class jet refuelling in flight']] },
  'kargil-vijay-diwas':             { hero:['tiger-hill.jpg','Tiger Hill, recaptured in the Kargil War'], inline:[['kargil-memorial-entrance.jpg','The entrance to the Kargil War Memorial at Drass']] },
  'agnipath-agniveer-scheme':       { hero:['tejas-mk1a.jpg','A modern Indian Air Force fighter — the force the Agniveers join'], inline:[['avani-chaturvedi.jpg','A newly commissioned officer of the Indian armed forces']] },
  'women-in-indian-armed-forces':   { hero:['avani-chaturvedi.jpg','Flying Officer Avani Chaturvedi, among India’s first women fighter pilots'], inline:[['republic-day.jpg','Armed forces personnel on parade']] },
  'atmanirbhar-bharat-defence':     { hero:['brahmos.jpg','The BrahMos missile, a symbol of indigenous defence capability'], inline:[['tejas.jpg','The home-built HAL Tejas fighter']] },
  'republic-day-india':             { hero:['republic-day.jpg','The Indian Army contingent at the Republic Day parade'], inline:[['t90-tank.jpg','A T-90 tank rolls down the parade route on Republic Day']] },
  'india-gate-amar-jawan-jyoti':    { hero:['india-gate.jpg','India Gate, New Delhi'], inline:[['amar-jawan-jyoti.jpg','The Amar Jawan Jyoti eternal flame']] },
  'a-soldiers-last-letter':         { hero:['kargil-memorial-entrance.jpg','The Kargil War Memorial, where many who wrote last letters are remembered'], inline:[['tiger-hill.jpg','Tiger Hill, a peak of the Kargil War']] },
  'the-history-of-indian-sovereignty': { hero:['salt-march.jpg','Mahatma Gandhi on the 1930 Salt March'], inline:[['gandhi-dandi.jpg','Gandhi reaching Dandi, April 1930'],['redfort-independence.jpg','The tricolour at the Red Fort']] },

  // ---- Batch 5 ----
  'field-marshal-cariappa':         { hero:['cariappa.jpg','Field Marshal K. M. Cariappa, India’s first Indian Commander-in-Chief'], inline:[['manekshaw.jpg','Field Marshal Sam Manekshaw, the second to hold the rank'],['republic-day.jpg','The Indian Army on parade']] },
  'general-bipin-rawat-cds':        { hero:['bipin-rawat.jpg','General Bipin Rawat, India’s first Chief of Defence Staff'], inline:[['republic-day.jpg','The Indian armed forces on parade']] },
  'indian-coast-guard':             { hero:['coast-guard.jpg','An Indian Coast Guard ship at sea'], inline:[['ins-vikrant.jpg','The Indian Navy, which the Coast Guard complements']] },
  'agni-missiles-india':            { hero:['agni-missile.jpg','An Agni ballistic missile launch'], inline:[['brahmos.jpg','The BrahMos cruise missile']] },
  'modern-indian-military-2026':    { hero:['republic-2025.jpg','Missile systems at the 2025 Republic Day parade'], inline:[['tejas.jpg','The indigenous HAL Tejas fighter']] },
  'battle-of-longewala-1971':       { hero:['t90-exercise.jpg','An Indian Army tank — heir to the armour that won at Longewala'], inline:[['army-mountains.jpg','Indian Army soldiers in the field']] },
  'arun-khetarpal-basantar':        { hero:['army-training.jpg','Indian Army soldiers in action'], inline:[['t90-tank.jpg','An Indian Army tank on parade — Khetarpal was an armoured-corps officer']] },
  'subedar-joginder-singh-1962':    { hero:['nathula-sikkim.jpg','The high Himalayan frontier where the 1962 war was fought'], inline:[['army-mountains.jpg','Indian soldiers at a high-altitude post']] },

  /* ---- contextual heroes so every article has its own image ---- */
  "national-war-memorial"             : { hero:["national-war-memorial.jpg","The National War Memorial in New Delhi"] },
  "param-vir-chakra"                  : { hero:["param-vir-chakra.png","The Param Vir Chakra, India's highest wartime gallantry award"] },
  "kargil-war-operation-vijay"        : { hero:["tiger-hill.jpg","Tiger Hill in Kargil, recaptured during Operation Vijay"] },
  "why-war-poetry-matters"            : { hero:["amar-jawan-jyoti.jpg","The eternal flame of remembrance for India's fallen soldiers"] },
  "india-china-border-dispute"        : { hero:["pangong-tso.jpg","Pangong Tso in Ladakh, along the disputed India–China frontier"] },
  "kashmir-geopolitics"               : { hero:["army-mountains.jpg","Indian Army soldiers at a high-altitude Himalayan post"] },
  "india-pakistan-relations"          : { hero:["1971-surrender.jpg","The Pakistani Instrument of Surrender signed in Dhaka, 1971"] },
  "neighbourhood-first"               : { hero:["nathula-sikkim.jpg","The Himalayan frontier at Nathu La, Sikkim"] },
  "saarc-bimstec"                     : { hero:["nathula-pass.jpg","The Nathu La pass, a historic trade route across the Himalaya"] },
  "act-east-policy"                   : { hero:["gorkha-bicentenary.jpg","Gorkha soldiers of the Indian Army on parade"] },
  "afghanistan-india"                 : { hero:["army-mountains.jpg","Soldiers in high, broken mountain terrain"] },
  "india-us-relations"                : { hero:["republic-day.jpg","India's Republic Day parade, where visiting heads of state are chief guests"] },
  "india-russia-relations"            : { hero:["t90-tank.jpg","An Indian Army T-90 tank, a mainstay of Indo-Russian defence cooperation"] },
  "brics-rise"                        : { hero:["republic-2025.jpg","Ceremonial display at India's Republic Day parade"] },
  "india-unsc-bid"                    : { hero:["india-gate.jpg","India Gate, New Delhi"] },
  "g20-india-presidency"              : { hero:["redfort-independence.jpg","The Red Fort in Delhi, where India marks Independence Day"] },
  "india-africa-relations"            : { hero:["gandhi-dandi.jpg","Mahatma Gandhi, whose political life began in South Africa, on the Dandi march"] },
  "india-middle-east"                 : { hero:["gateway-taj.jpg","The Gateway of India in Mumbai, India's historic maritime doorway"] },
  "taiwan-strait-global"              : { hero:["ins-vikrant.jpg","An Indian Navy aircraft carrier at sea"] },
  "arctic-geopolitics"                : { hero:["siachen.jpg","Soldiers on the ice of the Siachen Glacier"] },
  "energy-security-india"             : { hero:["coast-guard.jpg","An Indian Coast Guard vessel patrolling the sea lanes"] },
  "semiconductor-geopolitics"         : { hero:["tejas-mk1a.jpg","The indigenous Tejas fighter, built on advanced electronics"] },
  "malacca-dilemma"                   : { hero:["navy-submarine.jpg","An Indian Navy submarine, guarding the sea lanes"] },
  "indian-ocean-strategy"             : { hero:["coast-guard.jpg","An Indian Coast Guard ship on patrol in the Indian Ocean"] },
  "string-of-pearls"                  : { hero:["navy-submarine.jpg","An Indian Navy submarine on the surface"] },
  "chabahar-port"                     : { hero:["gateway-taj.jpg","The Gateway of India, Mumbai — a symbol of maritime trade"] },
  "space-geopolitics"                 : { hero:["agni-missile.jpg","An Agni missile on its launcher — the rocketry behind space power"] },
  "nuclear-doctrine-india"            : { hero:["agni-missile.jpg","The Agni missile, the delivery system of India's nuclear deterrent"] },
  "theatre-commands-india"            : { hero:["bipin-rawat.jpg","General Bipin Rawat, India's first Chief of Defence Staff"] },
  "drone-warfare-india"               : { hero:["iaf-rafale.jpg","A Rafale fighter of the Indian Air Force"] },
  "india-defence-exports"             : { hero:["brahmos.jpg","The BrahMos missile, India's flagship defence export"] },
  "hypersonic-missile-race"           : { hero:["brahmos.jpg","The supersonic BrahMos missile on display"] },
  "military-ai-india"                 : { hero:["tejas-mk1a.jpg","The Tejas Mk1A, a modern sensor-and-software-driven fighter"] },
  "red-sea-crisis-india"              : { hero:["ins-vikrant.jpg","An Indian Navy carrier at sea, projecting power across shipping lanes"] },
  "india-us-icet-tech"                : { hero:["tejas.jpg","The indigenous Tejas light combat aircraft"] },
  "cyber-electronic-warfare-india"    : { hero:["army-training.jpg","Indian Army soldiers on a field exercise"] },
  "india-submarine-fleet"             : { hero:["navy-submarine.jpg","An Indian Navy submarine, the silent arm of the deterrent"] },
  "military-space-india"              : { hero:["agni-missile.jpg","An Indian missile on its transporter-erector-launcher"] },
  "indian-air-power-fighters"         : { hero:["tejas.jpg","The Tejas, India's indigenously built fighter aircraft"] },
  "india-aircraft-carriers-navy"      : { hero:["ins-vikrant.jpg","INS Vikrant, India's indigenously built aircraft carrier"] },
  "agnipath-military-reform-india"    : { hero:["army-training.jpg","Indian Army recruits during training"] }
};

module.exports = { cr, MAP };
